### PR TITLE
Patch up PyPI requirements

### LINKED ISSUE #739: Ark Analysis can't install through PYPI
*Please refer to our [FAQ](https://ark-analysis.readthedocs.io/en/latest/_rtd/faq.html) and look at our [known issues](https://github.com/angelolab/ark-analysis/issues) before opening a bug report.*

**Describe the bug**

Currently Ark cannot be installed via PYPI. It is due to the `requirements.txt` file not being found. 

```sh
Collecting ark-analysis
  Using cached ark-analysis-0.4.1.tar.gz (296 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "/Users/srivarra/.pyenv/versions/3.8.13/envs/ark-3.8/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/Users/srivarra/.pyenv/versions/3.8.13/envs/ark-3.8/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/srivarra/.pyenv/versions/3.8.13/envs/ark-3.8/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/fy/q2szypn9325d_0g0nq049k300000gq/T/pip-build-env-ro_zvi_n/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/private/var/folders/fy/q2szypn9325d_0g0nq049k300000gq/T/pip-build-env-ro_zvi_n/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/fy/q2szypn9325d_0g0nq049k300000gq/T/pip-build-env-ro_zvi_n/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 482, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/private/var/folders/fy/q2szypn9325d_0g0nq049k300000gq/T/pip-build-env-ro_zvi_n/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 21, in <module>
      FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/fy/q2szypn9325d_0g0nq049k300000gq/T/pip-install-__yl7pxm/ark-analysis_442d8caf3e654a1482fb20edd3df73f3/requirements.txt'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Expected behavior**

It should gather the requirements properly and install them, alongside `Ark` directly.

**To Reproduce**

Run `pip install ark-analysis` in a fresh python environment.

### PR DESCRIPTION
**Pull request by alex-l-kong**
**What is the purpose of this PR?**

Closes #739. The `requirements.txt` file is not being reference properly, this needs to be patched.

**How did you implement your changes**

The `requirements.txt` file is actually copied over to `ark_analysis.egg-info/requires.txt` on PyPI (or when `python3 -m build` is called), so this path will need to be used instead. It copies the test modules over too, so we need to remove those.

Additionally, we need to ensure that the `_bootstrapping` module builds correctly, referencing the `_bootstrapping.c` file should do the trick.

### CODE REVIEW

**Comment by alex-l-kong** [comment]
@ngreenwald not the cleanest solution but it solves our problems for the time being. `twine` works on TestPyPI and making a new release should upload to PyPI correctly too (build process is the same outside of the endpoint we're uploading to).

Tested out a few non-R-dependent functions with the TestPyPI `pip install` of `ark-analysis` and they work.

GitHub Actions will be the next step in this process.

**Review by ngreenwald — CHANGES_REQUESTED** [review]
"github actions next" meaning that in order to make it cleaner that's the best solution, or in order for it to work properly that's required?

**Comment by alex-l-kong** [comment]
> "github actions next" meaning that in order to make it cleaner that's the best solution, or in order for it to work properly that's required?

To provide a cleaner solution. However, it works fine as it is right now.

**Review by ngreenwald — APPROVED** [review]
Okay looks good, you can draft a new release when you have some time to make sure it works as expected.

**Comment by ngreenwald** [comment]
Actually, lets wait until all three example dataset PRs are merged in, that'll be a good savepoint anyway

**Pull request merged**
