### PR TITLE
Refactor marker quantification

### LINKED ISSUE #185: Code cleanup for segmentation
Marker_quantification.py:
Is there a better way to distinguish `generate_expression_matrix` and `compute_complete_expression_matrix`? These function names aren't that informative
testing: Many of the test functions here are too long. We should break them up into smaller test functions, named by which aspect of the main function they're testing, so that when errors are raised it's more obvious based on the name of the test that's failing what the problem was. 

Signal_extraction.py:
Testing: import the synthetic_data function with a (much) shorter name to increase code readability. 

I'm not in love with marker_quantification as the module name here. Open to suggestions for a good name to describe the set of functions that take segmentation masks, channel data, and produce the CSV of counts per cell.

### PR DESCRIPTION
**Pull request by alex-l-kong**
**What is the purpose of this PR?**

Addresses and closes #185.

**How did you implement your changes**

Rename some functions in `marker_quantification.py` to something more understandable. Split up the test functions in `marker_quantification_test.py`.

### CODE REVIEW

**Comment by alex-l-kong** [comment]
Note sure why this PR isn't being submitted to Travis, but I tested it locally and it passes all the tests.

**Review by ngreenwald — CHANGES_REQUESTED** [review]
That's so strange. Maybe try pushing another commit?

**Comment by alex-l-kong** [comment]
Alright, Travis is back online!

**Review by ngreenwald — APPROVED** [review]
Sweet, looks good

**Pull request merged**
