### PR TITLE
Split nuclei bugfix

### PR DESCRIPTION
**Pull request by ngreenwald**
**If you haven't already, please read through our [contributing guidelines](https://ark-analysis.readthedocs.io/en/latest/_rtd/contributing.html) before opening your PR**

**What is the purpose of this PR?**
The current split_nuclei logic first modifies the nuclear segmentation mask, and then uses that modified mask to extract signal. However, it doesn't provide that modified mask to the regionprops function, which results in a mismatch between the outputs from the two

**How did you implement your changes**
I passed in the modified nuclear segmentations to the regionprops function so that the outputs match up. I also switched the min_size value to match up with the current min_size from Mesmer

**Remaining issues**
We don't pass these modified nuc masks back to the user, but given that this setting is turned off by default I think that's okay for now.

### CODE REVIEW

**Review by alex-l-kong — APPROVED** [review]
Looks good!

**Review by ackagel — COMMENTED** [review]
any reason we don't overwrite the unmodified nuclear mask with the modified one?

**Comment by ngreenwald** [comment]
Yeah I wasn't sure what the best approach would be. We could save over the deepcell output directly?

**Comment by ackagel** [comment]
is splitting the big nuclei a toggle-able option for the user?  I think we can overwrite as long as we're informing and/or putting the onus on the user

**Comment by ngreenwald** [comment]
Yes, in theory it's toggle-able, but right now the kwarg isn't passed to the top-level function and it defaults to False. 

I think your suggestion makes sense once we give users the option of enabling this. For now, there hasn't been demand for it, so I'm going to leave it hidden and off to keep things simple until we start hearing issues from people re: large nuclei

**Review by ackagel — APPROVED** [review]

**Pull request merged**
