### PR TITLE
Github Actions - Merge Queue

### LINKED ISSUE #931: Enable CI workflow to mesh with merge queue
**Is your feature request related to a problem? Please describe.**
Github released a new beta feature that allows you to create a merge queue. If you have a bunch of approved PRs, you can add them to the queue, and they'll auto update one at a time, and assuming no errors, get merged in. This prevents you having to update each PR separately with the new changes after a different approved PR gets merged in. 

The issue is that this merge queue is not a branch or a PR, but a separate entity. This means we need to tell all of our CI tools about this additional feature so they know to get triggered. There's more details here: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue

I've enabled it on our repo, so you should be able to test things out.

### PR DESCRIPTION
**Pull request by srivarra**
**If you haven't already, please read through our [contributing guidelines](https://ark-analysis.readthedocs.io/en/latest/_rtd/contributing.html) before opening your PR**

**What is the purpose of this PR?**

Closes #931.
**How did you implement your changes**

Adds merge queue, removes python Dependabot.

**Remaining issues**

N/A.

### CODE REVIEW

**Comment by ngreenwald** [comment]
I think we’ll need to tweak readthedocs as well? Did you take a look at what’s required there?

**Comment by srivarra** [comment]
@ngreenwald What did we need to tweak for readthedocs? It seems to be building properly. Is it the older package requirements that it uses?

**Review by ngreenwald — APPROVED** [review]
I think it doesn't work with merge queues. Let's see how it goes.

**Comment by ngreenwald** [comment]
Test failed because out of disk space. You can also see that it's currently waiting for the RTD to build. 
image

**Comment by srivarra** [comment]
@ngreenwald Tried to restart the CI workflow in the merge queue, however there was no response coming from the workflow request. After 12 min of no responses it kicked the PR off the merge queue. Alex's [latest 2](https://github.com/angelolab/ark-analysis/actions/runs/4236373325) run also did not start successfully.

**Comment by ngreenwald** [comment]
I merged this in, so at least the GA part of the merge queue will be working. RTD doesn't know to look for a merge queue. There's a description in the link I posted in the issue about what to do for non-GA integration. 

Separately, we'll need to free up space on GA

**Pull request merged**
