### PR TITLE
Add _rtd folder for documentation to explain MIBI/ARK in more detail

### LINKED ISSUE #213: Create layout for documentation files
The next step for our documentation is to start organizing the various files we're going to have on the RTD landing page. Currently, it pulls from the ReadMe and the docstrings. However, there are a number of additional files we're going to have for giving more in-depth explanation of different parts of the pipeline. Likely we won't just to paste them all in the readme. Instead, we'll have markdown versions of the files stored in the docs section of the github, and these can get rendered on readthedocs. 

Let's put together an example layout of what that would look like. There's a lot of flexibility here in terms of organization, so feel free to adapt any of these suggestions if you have ideas. 

The landing page: This should have the basic information about the repo, and link to the following:

Getting started for users: installation instructions using docker and bash script
getting started for developers: virtual-env instructions
Overview of the pipeline (#211)
Overview of different data types (#210), including xarrays (#209)
A link to our contributing guidelines (currently in docs)

What would be great is to create a placeholder file to represent each of these categories, so that we can see how it will look on RTD, how to link from one to another, etc. If you have other ideas for useful sections feel free to make a mockup of them as well. 

Then, once we're happy with the organization, we can actually go in and fill in the content for each of them.

### PR DESCRIPTION
**Pull request by alex-l-kong**
**What is the purpose of this PR?**

Addresses and closes #213. Currently, our ReadTheDocs page only supports a basic landing page and documentation. We want to have some more information to guide our users through how the actual pipeline works, how to set up their virtual environment, etc. We also want to make our ReadTheDocs site more sophisticated.

**How did you implement your changes**

We create a separate `_rtd` folder which will contain `.md` files we can link to in `index.rst` (specifically the `toctree`) which each explain a certain aspect of our work. We will also be updating our `index.rst` file to integrate these new files into the table of contents (aka the `toctree`).

**Remaining issues**

I have a set of template `.md` pages attached, but we may need to add/delete some of them. Please note that this PR only addresses the structure for our documentation moving forward. We will have another PR (or PRs) which will handle adding the meat to these `.md` files.

### CODE REVIEW

**Comment by alex-l-kong** [comment]
I still need to figure out how to get the Home page automatically selected in Sphinx, but I'm sure it's pretty easy to do. For now, would appreciate comments on the directory structure as well as how everything appears on ReadTheDocs (click "Details" next to the readthedocs badge to view).

For the record, Noah's `contributing.md` parses very nicely. When we actually start adding contents to these files, it would be good to follow the style he used for that `.md` file.

**Comment by ngreenwald** [comment]
This looks great! It auto-generated sections based on the .md file headings. I notice that there's a hyperlink option for the sub-headings: is the best way to link from different docs to one another to embed the hardcoded absolute path to that heading, or is there some way we should use relative links or something within the docs? I remember you mentioning this before at one point

**Review by ackagel — COMMENTED** [review]
looking great so far!  I don't mind adding some stuff to the virtualenv file once this is merged in, with info on how to set up development within a docker container in VSCode

**Review by saeedseyyedi — COMMENTED** [review]
Looks good so far!

**Comment by alex-l-kong** [comment]
> This looks great! It auto-generated sections based on the .md file headings. I notice that there's a hyperlink option for the sub-headings: is the best way to link from different docs to one another to embed the hardcoded absolute path to that heading, or is there some way we should use relative links or something within the docs? I remember you mentioning this before at one point

I think for now, it's OK to use the absolute path. It looks like DeepCell uses the same thing. If by any chance you're talking about how index.rst's toctrees are formatted (Tab <path_to_md_file>), then that's because this is the .rst way to alias your file to a better-looking name.

**Review by ngreenwald — APPROVED** [review]
Okay great, we can use the full url links in that case

**Pull request merged**
