### PR TITLE
Improve jupyter launching (Jupyter Lab + enhanced alternate PORT)

### PR DESCRIPTION
**Pull request by y2kbugger**
**What is the purpose of this PR?**

- Launch **Jupyter** as **Jupyter Lab** instead of **Jupyter Notebook**
- Enhance `start_docker.sh` to pass the first available port to jupyter so that "remapped port" warning is no longer required.
- Enhance available port detection to be more reliable
- Add execute to start_docker.sh to allow running directly, updated readme to match.

**How did you implement your changes**

I've touched start_docker.sh and Dockerfile.
For details, see commit history as I have broken up commits to tell story clearly.

**Remaining issues**

None

### CODE REVIEW

**Comment by y2kbugger** [comment]
@ngreenwald Figured we could merge this into master prior to finalizing the metacluster GUI.

**Review by ngreenwald — COMMENTED** [review]
Overall looks good! Is there a code cleanliness reason that having the script be executable is preferable to running bash scriptname? Or just a personal preference?

**Comment by y2kbugger** [comment]
> Overall looks good! Is there a code cleanliness reason that having the script be executable is preferable to running bash scriptname? Or just a personal preference?

I'd say it follows "least astonishment" since it allows both `bash ./script.sh` and `./script.sh`and different people might be used to one or another.
Marking as executable also made sense since the script already included a the "hash-bang" (`#!`), which does nothing if not ran directly.

*start_docker.sh*

    #!/bin/bash
    ...

**Comment by y2kbugger** [comment]
I did just push a small change, to use the _slightly_ more portable `#!/usr/bin/env bash` ipo `#!/bin/bash`

https://stackoverflow.com/questions/10376206/what-is-the-preferred-bash-shebang

**Review by ngreenwald — APPROVED** [review]
Got it, that all makes sense.

**Pull request merged**
