### PR TITLE
Adds np array support to verify in list

### LINKED ISSUE #583: verify_in_list numpy array conversion
## **Description**
The `verify_in_list` utility function doesn't support numpy arrays.  There's code that attempts this conversion via `[*]` wrapping the array, but this just generates a singleton list with the array as it's single element.  This conversion needs to be changed to `list(*)`.

## **To Reproduce**
Pass numpy arrays to `verify_in_list`

## **Expected behavior**
Numpy arrays should be supported.

## **Screenshots**
Offending lines:
Screen Shot 2022-06-01 at 3 02 53 PM

### LINKED ISSUE #585: Image on Dockerhub does not include `spatial_lda` and `palettable` libraries
**Describe the bug**

Spinning up a Jupyter notebook using the current Docker instance will cause import errors with the `spatial_lda` and `palettable` libraries.

**To Reproduce**

Start up Docker locally, and run a notebook that requires and explicit or implicit import `spatial_lda` import.

**Expected behavior**

The libraries `spatial_lda` and `palettable` should be imported without error.

### PR DESCRIPTION
**Pull request by ackagel**
Addresses issue #583 .  Also adds test case for array compliance.  Closes #583, and closes #585.

### CODE REVIEW

**Review by alex-l-kong — APPROVED** [review]
Looks good to me

**Comment by ngreenwald** [comment]
Will you trigger a new docker build as well to take care of #585

**Comment by ackagel** [comment]
@alex-l-kong looks like it pushed an image to dockerhub. Can you verify that #585 isn't a problem with that image?

**Comment by alex-l-kong** [comment]
@ackagel it works.

**Review by ngreenwald — APPROVED** [review]

**Pull request merged**
