### PR TITLE
Ark Pipeline Flowchart

### LINKED ISSUE #211: Flowchart for analysis pipeline
As we continue to add more pieces to the pipeline, I think it would be useful to have a graphical representation of how data moves through the different scripts. This would be related to a description of individual data types (#210), and we would likely link to it. It would also likely link to the example notebooks. I imagine this going in the main readme section to serve as a starting point for understanding the repo

### PR DESCRIPTION
**Pull request by srivarra**
**If you haven't already, please read through our [contributing guidelines](https://ark-analysis.readthedocs.io/en/latest/_rtd/contributing.html) before opening your PR**

**What is the purpose of this PR?**

Closes #211.

**How did you implement your changes**

Added a pipeline flowchart for the ark notebooks.

**Remaining issues**

Should we consider renaming `example_spatial_analysis_script` to reflect that it's using spatial pairwise enrichment?

### CODE REVIEW

**Comment by ngreenwald** [comment]
Yes, I think more informative names for the notebooks would be great. Talk to the people presenting that section of the workshop to coordinate with them. 

Also, the outputs of the entire process of column 1 are needed for the spatial stuff, not just segmentation, so the line should come from the bottom. 

The PR I currently have open for post-clustering modifications can get swapped in where the `visualization` notebook currently is.

**Comment by srivarra** [comment]
@ngreenwald

**Review by ngreenwald — CHANGES_REQUESTED** [review]
Will you update the name of the post-clustering notebook, and also include it in the box with segmentation and clustering?


Also center the names of everything: pixie pipeline, spatial analysis, spatial LDA, etc.

**Comment by ngreenwald** [comment]
Last thing, dotted arrow should come from the whole clustering pipeline box, not the middle before post-clustering

**Review by ngreenwald — APPROVED** [review]
Looks great!

**Pull request merged**
