### PR TITLE
Add a new notebook for neighborhood analysis

### LINKED ISSUE #282: Add notebook specifically for neighborhood analysis
**Describe the solution you'd like**

In line with Erin's desired pipeline (#139), we will be addressing some more steps (ex. adding a visualization overlay of each neighborhood cluster onto a segmented image) for neighborhood analysis. With the additional steps of running the k-means clustering processes beforehand, we'll create a separate notebook to handle this.

### PR DESCRIPTION
**Pull request by alex-l-kong**
**What is the purpose of this PR?**

Addresses and closes #282. With a pipeline for neighborhood analyses nearly complete, we create a specific notebook to run neighborhood analysis with the clustering steps and a stub for overlaying the segmented cells with their respective neighborhood clusters.

**How did you implement your changes**

Add a new notebook, `example_neighborhood_analysis_script.ipynb`.

**Remaining issues**

Overall comments on the structure of the notebook would be appreciated.

### CODE REVIEW

**Comment by alex-l-kong** [comment]
The notebook is likely not at a finished stage yet, just overall reviews for what's been done so far.

**Review by ngreenwald — CHANGES_REQUESTED** [review]
Looks nice! The other to-do section to put in there is the heatmap/dendrogram that Erin mentioned in the main issue.

**Review by ngreenwald — CHANGES_REQUESTED** [review]
Looks good. Can you add the notebook to Travis as well?

**Comment by alex-l-kong** [comment]
> Looks good. Can you add the notebook to Travis as well?

Sure, sorry I forgot.

**Review by ngreenwald — APPROVED** [review]
Looks good. Can you close the 'next steps for processing pipeline` issue and create individual issues for the remaining todos in this notebook?

**Pull request merged**
