### PR TITLE
Extended Attributes on macOS

### LINKED ISSUE #936: cluster_pixels function fails to delete pixel_mat_data folder
**Describe the bug**
Cluster_pixels function works as intended on a test set of 28 images. But when using a larger set of data (604 FOVs), the following error is generated after all 604 FOVs have been processed (attempted this 2 times to confirm) 

" [Errno 2] No such file or directory: '/Volumes/Elite Pro/DCIS/Cohorts/20230209_DCIS/pixie/Round_1_attemp_2_pixel_output_dir/pixel_mat_data/._TA583_R8C5.feather'"

Screenshot 2023-02-22 at 10 21 31 AM

Upon inspecting the data directory -  the pixel_mat_data and pixel_mat_data_temp are both still present. However, in pixel_mat_data folder there are only 603 FOVs (TA583_R8C5.feather file indicated in the error above has been deleted) while in pixel_mat_data_temp folder there are the 604 FOVs. 

Screenshot 2023-02-22 at 10 26 31 AM

Screenshot 2023-02-22 at 10 27 17 AM

Screenshot 2023-02-22 at 10 27 48 AM

### PR DESCRIPTION
**Pull request by srivarra**
**If you haven't already, please read through our [contributing guidelines](https://ark-analysis.readthedocs.io/en/latest/_rtd/contributing.html) before opening your PR**

**What is the purpose of this PR?**

Closes #936. Fixes an issue with `cluster_pixels` where on macOS, the meta file (prefixed with "._") gets unlinked when the original file gets unlinked.

**How did you implement your changes**

Added the solution described in the issue post. The test tests that the logic of that function works appropriately, but not testing it's usage in `rmtree`.

**Remaining issues**

N/A

### CODE REVIEW

**Comment by srivarra** [comment]
@camisowers @alex-l-kong Do you guys have any suggestions on testing this? I'm not too sure how to go about it.

**Comment by alex-l-kong** [comment]
You could try creating some dummy ._ files within a folder recursively to see if it works.

I've been using `subprocess.call(["find", folder_path, "-type", "f", "-name", "._*-delete"])` prior to `shutil.rmtree` in Rosetta to handle this, seems to work just as well. I think Noah suggested that this approach might be easier, reason being we don't use `shutil.rmtree` very often for external drives.

@ngreenwald can you confirm which solution you feel is better?

**Review by camisowers — APPROVED** [review]
Looks good.

**Review by alex-l-kong — APPROVED** [review]
👍

**Pull request merged**
