### PR TITLE
Remove anything Docker related from the README

### LINKED ISSUE #1145: Windows Problem With bash start_docker.sh Command
Hello!

I am attempting to install this package today to use Pixie on a Windows machine. I have made it through the installation tutorial up to the step "Setting up the repo". 

Everything seems to be working well until I execute the line `bash start_docker.sh` in the command prompt terminal. The outcome is the error message in the image below. I ran `wsl sudo apt-get install dos2unix` and then retried, but this did not work for me. 

Please let me know if there is a solution to this problem. I look forward to your response and thank you in advance!

image

### PR DESCRIPTION
**Pull request by alex-l-kong**
**What is the purpose of this PR?**

Closes #1145. Due to issues users have had trying the Docker setup, it's best for the general public not to use this setup.

**How did you implement your changes**

Remove anything from the `README.md` about Docker setup. Instead, provide detailed instructions for using `conda` environments and `./start_jupyter.sh`.

### CODE REVIEW

**Comment by alex-l-kong** [comment]
@cliu72 the failing tests are due to the ongoing pytorch issue (https://github.com/angelolab/ark-analysis/issues/1150)

**Review by camisowers — CHANGES_REQUESTED** [review]
Since the conda env will be the way we support ark from now on, could use a little more info on how to maintain it like we have written up in toffy. For example, an [updating the repo](https://github.com/angelolab/toffy?tab=readme-ov-file#updating-the-repo) section is probably necessary.

**Review by srivarra — APPROVED** [review]

**Review by srivarra — CHANGES_REQUESTED** [review]
@alex-l-kong I think we can also remove all docker functionality in this PR such as the [Dockerfile](https://github.com/angelolab/ark-analysis/blob/301e344f0ffbedafaad282c52c801e7713272f85/Dockerfile), and the [docker.yml](https://github.com/angelolab/ark-analysis/blob/301e344f0ffbedafaad282c52c801e7713272f85/.github/workflows/docker.yml) workflow. What do you think, or we can toss that into another issue?

**Comment by alex-l-kong** [comment]
> @alex-l-kong I think we can also remove all docker functionality in this PR such as the [Dockerfile](https://github.com/angelolab/ark-analysis/blob/301e344f0ffbedafaad282c52c801e7713272f85/Dockerfile), and the [docker.yml](https://github.com/angelolab/ark-analysis/blob/301e344f0ffbedafaad282c52c801e7713272f85/.github/workflows/docker.yml) workflow. What do you think, or we can toss that into another issue?

@srivarra I can remove the Docker badge from this PR. The complete removal of Docker I wanted to save for a different PR. Mostly because I think it'll still be good to have around as legacy. Main goal is to keep this hidden from the instruction manual as much as possible so it doesn't confuse users.

**Comment by srivarra** [comment]
@alex-l-kong Sounds good to me!

**Review by camisowers — APPROVED** [review]
Nice

**Review by srivarra — APPROVED** [review]

**Pull request merged**
