### PR TITLE
Remove cell table batching functionality

### PR DESCRIPTION
**Pull request by alex-l-kong**
**What is the purpose of this PR?**

Addresses stage 1 of #720, removing batching of `generate_cell_table`.

**How did you implement your changes**

The batch loop inside `generate_cell_table` has been changed to a per-FOV iteration.

The call in `1_Segment_Image_Data.ipynb` needed to be updated accordingly.

**Remaining issues**

In particular, changes were made to the way `fovs` and `filenames` were being handled in `generate_cell_table`. MIBItiff support requires us to retrieve `filenames`, however for non-MIBItiffs the loop needs to be more fully guarded against `filenames` being set to `None` (which happens when you call `list_files` on a folder structure).

We will not have to worry about this once MIBItiff support gets phased out.

### CODE REVIEW

**Comment by alex-l-kong** [comment]
@benoberlton this PR should address the error caused by variable image sizes you were getting during `generate_cell_table`. Let me know if any issues pop up.

**Comment by alex-l-kong** [comment]
@ngreenwald realized I needed to update the documentation for `create_marker_count_matrices` to indicate that the FOV dimensions should support just a single FOV, however seems I can't push the change until you review the rest of the changes (even if I remove the review request). If all looks good I'll push that change separately.

**Review by ngreenwald — CHANGES_REQUESTED** [review]
Huh that's strange, I didn't know review status could block subsequent changes. Won't have time to look tonight, I'll submit this which will hopefully address the issue

**Review by ngreenwald — CHANGES_REQUESTED** [review]
Looks good, just need to add back in the code that was removed. Seems like this has happened a bunch of times on your PRs, I think you said your editor does it automatically?

**Comment by alex-l-kong** [comment]
> Looks good, just need to add back in the code that was removed. Seems like this has happened a bunch of times on your PRs, I think you said your editor does it automatically?

@ngreenwald yeah, looks like I'll need to officially need to retire my merge tool lol, Sublime Merge hasn't been the easiest to interface with.

**Comment by alex-l-kong** [comment]
@ngreenwald this should resolve `generate_cell_table` with `main`.

**Review by ngreenwald — APPROVED** [review]

**Pull request merged**
