### PR TITLE
Enrichment distance hack

### PR DESCRIPTION
**Pull request by ackagel**
## **Purpose**

Adds feature distance columns to spatial enrichment analysis.

## **Implementation**

Appends rows to cell table representing desired 'feature', and appends row+col to distance matrix representing said feature.  Also adds basic coverage test.

## **Remaining issues**

Testing for positive, negative, and neutral enrichments.  This will be covered in a post-workshop pr

### CODE REVIEW

**Comment by ackagel** [comment]
pretty sure this is the last part of the spatial enrichment update, unless we want to further update the notebooks w/ prettier figures.  Feedback on the "distance hack" implementation would be appreciated.

**Comment by ngreenwald** [comment]
Cool, will you get @cliu72 and Inna to take a look as well?

**Comment by ackagel** [comment]
sure, I'll add @cliu72 as a reviewer, and I'll see if I can get Inna's input Monday; we're going over a demo run through of this then, so I'll just have her pull from this branch when we do that.

**Comment by ackagel** [comment]
@ngreenwald

**Review by ngreenwald — APPROVED** [review]
Looks good to me, once Inna approves fine to merge in

**Pull request merged**
