### PR TITLE
Delete .github/ISSUE_TEMPLATE directory

### PR DESCRIPTION
**Pull request by ngreenwald**
**If you haven't already, please read through our [contributing guidelines](https://ark-analysis.readthedocs.io/en/latest/_rtd/contributing.html) before opening your PR**

**What is the purpose of this PR?**
Removes the old templates in `ark` so that the repo-wide files will apply

### CODE REVIEW

**Comment by ngreenwald** [comment]
@srivarra because of the release-drafter stuff in the `ark` .github folder, I'm not sure if just removing these files will be enough for it to pull from the repo-wide .github templates directory. I'm guessing we'll need to completely delete this folder in order for it to use the angelolab defaults, which means we'll need to migrate the release-drafter stuff

**Comment by srivarra** [comment]
@ngreenwald Yeah, we can get rid of this folder, and then angelolab/.github should be applied to each repository in the org.

**Review by srivarra — APPROVED** [review]
Lets give it a try.

**Comment by ngreenwald** [comment]
Looks like it's only popping up in the .github repo, not anywhere else. Maybe you can't have orgnaization-wide github actions?

**Pull request merged**
