### PR TITLE
Notebook Reorganization

### LINKED ISSUE #590: Update readme
**Is your feature request related to a problem? Please describe.**
The current readme is getting a bit long, and could use a reorg. In addition, the number of different notebooks has also proliferated. We should reorganize the structure to resemble to the toffy repo.

### LINKED ISSUE #640: Numbering the Template Jupyter Notebooks
**Is your feature request related to a problem? Please describe.**

Currently the template jupyter notebooks in ark/templates_ark are not numbered (such as in angelolab/toffy).

**Describe the solution you'd like**
Add a numbering prefix to each of the notebooks.

**Describe alternatives you've considered**
N/A

**Additional context**

### PR DESCRIPTION
**Pull request by ngreenwald**
**If you haven't already, please read through our [contributing guidelines](https://ark-analysis.readthedocs.io/en/latest/_rtd/contributing.html) before opening your PR**

**What is the purpose of this PR?**

Reorganizes the notebooks to be more in line with toffy. Closes #640, closes #590 

**Remaining issues**
The links, table of contents, etc in readme will need to be updated. The testbook stuff will need to be updated

### CODE REVIEW

**Comment by srivarra** [comment]
@ngreenwald I can't seem to request a review for this. How does it look?

**Comment by ngreenwald** [comment]
Overall looks really nice. 

I think the outline could use some more formatting:
image

Maybe one section on using the repo, which would include the first three bullets. 
Giving Mantis it's own section, rather than a subheading under the unrelated "Once you are finished" tab. Etc etc. Then update the headers to be the appropriate size based on the hierarchical formatting

**Comment by srivarra** [comment]
@ngreenwald I've adjusted the organization a bit more. How does it look?

**Comment by ngreenwald** [comment]
Looks great!

**Pull request merged**
