### PR TITLE
Ensure channel norm and pixel norm files get re-computed if a new set of channels are provided

### LINKED ISSUE #599: Pixel data preprocessing - operand broadcast error
*Please refer to our [FAQ](https://ark-analysis.readthedocs.io/en/latest/_rtd/faq.html) and look at our [known issues](https://github.com/angelolab/ark-analysis/issues) before opening a bug report.*

**Describe the bug**
Running the pixel data preprocessing block of code in pixel clustering notebook, and getting an error
 "ValueError: operands could not be broadcast together with shapes (2048,2048,33) (1,1,35)"

**To Reproduce**
I ran this notebook over the weekend with no issues on my personal laptop, but didn't have sufficient docker space. Moved to desktop computer with increased space today. Updated code before rerunning, and now have an error in the pixel data preprocessing step. 

**Screenshots**
Screen Shot 2022-06-14 at 12 59 44 PM

### PR DESCRIPTION
**Pull request by alex-l-kong**
**What is the purpose of this PR?**

Closes #599. The underlying issue is if the user provides a different set of channels on a `pixel_output_dir` that has an existing `channel_norm.feather` computed on a different set of channels.

**How did you implement your changes**

We need to ensure that the set of channels provided when loading in an existing `channel_norm.feather` match the `channels` argument set-wise. If they don't, then we simply re-compute and re-save.

The same needs to be done for `pixel_norm.feather`. We store a checkpoint during the `channel_norm.feather` check to ensure this can happen seamlessly for the pixel norm too.

### CODE REVIEW

**Comment by alex-l-kong** [comment]
@ngreenwald normally, the step of regenerating the FOVs gets skipped if all the FOV `.feather` files exist, however these will also need to be re-generated if a new set of `channels` are provided to an existing `channel_norm.feather`. Will need to spend a bit more time testing this one.

**Comment by ngreenwald** [comment]
Maybe if the norm_files need to be regenerated, have a warning to the user saying different parameters were detected, then delete the norm files and the feather files. Then none of the downstream logic has to change.

**Comment by alex-l-kong** [comment]
> Maybe if the norm_files need to be regenerated, have a warning to the user saying different parameters were detected, then delete the norm files and the feather files. Then none of the downstream logic has to change.

This works. Only additional thing is to delete all the existing preprocessed FOVs as well (to prevent downstream logic from not recomputing these).

**Review by ngreenwald — APPROVED** [review]
Looks good!

**Pull request merged**
