### PR TITLE
Temporarily remove pixel preprocessing normalization for Candace's paper

### PR DESCRIPTION
**Pull request by alex-l-kong**
**What is the purpose of this PR?**

@cliu72 will need to remove `channel_norm_df` normalization and `pixel_thresh` from the pixel preprocessing step of Pixie.

**How did you implement your changes**

Explicitly remove both of these processes.

**Remaining issues**

See discussion thread.

### CODE REVIEW

**Comment by alex-l-kong** [comment]
@cliu72 is it fine to leave in the computations of `channel_norm_df` and `pixel_thresh_df` as long as they're not used for preprocessing, or would the reviewers need all references to these completely purged?

**Comment by cliu72** [comment]
> @cliu72 is it fine to leave in the computations of `channel_norm_df` and `pixel_thresh_df` as long as they're not used for preprocessing, or would the reviewers need all references to these completely purged?

I think it's okay to leave in the computations to make it easier for later, but can we remove writing those files? The files with the 99.9% value and the pixel threshold value. I think having those files written will be confusing.

**Comment by alex-l-kong** [comment]
@cliu72 we're aiming to get this PR merged in by Friday so we can close out as many open Pixie issues as possible before your submission.

**Review by cliu72 — APPROVED** [review]
Looks good!

**Review by ngreenwald — CHANGES_REQUESTED** [review]
Lets wait to merge this in until all of the other PRs are merged in, as well as after all the testing candace does, to make sure that undoing this is as simple as possible.

**Comment by alex-l-kong** [comment]
@ngreenwald @cliu72 with the overwrite branch now merged into `main`, I think that concludes all the dependencies for this task. If we're ready, we can merge this PR in and tag this as the main release.

**Comment by cliu72** [comment]
I'm going to do one more check over everything, which I'll do hopefully today/tomorrow. I think we can wait to merge this PR then after that.

**Review by ngreenwald — CHANGES_REQUESTED** [review]
Not sure what happened here, but none of the changes are present anymore

**Comment by alex-l-kong** [comment]
Oh that's weird, let me fix that up again.

**Comment by alex-l-kong** [comment]
Looks like GitHub had trouble mapping the changes into pixie_preprocessing.py. Should be good to go now!

**Comment by cliu72** [comment]
I don't think all the changes have been re-implemented after the merge conflicts. These lines should be gone (were removed in the original review):

https://github.com/angelolab/ark-analysis/blob/8efc712645595c6f8e40f7996fa43d3c1a3a6b96/src/ark/phenotyping/pixie_preprocessing.py#L68-L70

https://github.com/angelolab/ark-analysis/blob/8efc712645595c6f8e40f7996fa43d3c1a3a6b96/src/ark/phenotyping/pixie_preprocessing.py#L152-L157

After thinking on it some more, I think it would be best to remove these too (to avoid confusion):
https://github.com/angelolab/ark-analysis/blob/8efc712645595c6f8e40f7996fa43d3c1a3a6b96/src/ark/phenotyping/pixie_preprocessing.py#L258-L284

https://github.com/angelolab/ark-analysis/blob/8efc712645595c6f8e40f7996fa43d3c1a3a6b96/src/ark/phenotyping/pixie_preprocessing.py#L322-L347

Remove `channel_norm_df` and `pixel_thresh_val` as inputs to `preprocess_fov`

**Comment by alex-l-kong** [comment]
@cliu72 OK this should do the trick.

**Pull request merged**
