### PR TITLE
Fixed FlowSOM on Docker Image

### PR DESCRIPTION
**Pull request by srivarra**
**If you haven't already, please read through our [contributing guidelines](https://ark-analysis.readthedocs.io/en/latest/_rtd/contributing.html) before opening your PR**

**What is the purpose of this PR?**

Adds the line to include the original FlowSOM back into the Docker.

**How did you implement your changes**

Adjusted `Dockerfile`.

**Remaining issues**

None.

### CODE REVIEW

**Review by alex-l-kong — APPROVED** [review]

**Review by ngreenwald — CHANGES_REQUESTED** [review]
Looks like there's a pypi error. Why do we need both flowsoms?

**Comment by srivarra** [comment]
The first flowsom installs the dependencies that the forked version uses. The PyPI error is fine. There is a v0.4.1 that for uploaded earlier today.

**Comment by ngreenwald** [comment]
kk sounds good, you can do that from travis right?

**Comment by srivarra** [comment]
> kk sounds good, you can do that from travis right?

Yup

**Pull request merged**
